server:
  port: 8000

spring:
  application:
    name: Reservation-gateway
  cloud:
    gateway:
#      default-filters:
#        - name: "CustomGlobalFilter"
#          args:
#            logging: "true"
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-main-service
          uri: "lb://AUTH-MAIN-SERVICE"
          predicates:
              - Path=/api/v1/authmain/**
        - id: auth-service
          uri: "lb://AUTH-SERVICE"
          predicates:
            - Path=/api/v1/auth/**
        - id: myUser-service
          uri: "lb://USER-SERVICE"
          predicates:
            - Path=/api/v1/user/**
        - id: owner-service
          uri: "lb://OWNER-SERVICE"
          predicates:
            - Path=/api/v1/owner/**
        - id: customer-service
          uri: "lb://CUSTOMER-SERVICE"
          predicates:
            - Path=/api/v1/customer/**

management:
  endpoints:
    web:
      exposure:
        include: health,beans,refresh


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}